aflp/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from rest_framework_jwt.views import obtain_jwt_token,refresh_jwt_token
urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('core.urls')),
    path('', include('shortu.urls')),
    path('', include('news.urls')),
    path('', include('cw.urls')),
    path('rest-auth/', include('rest_auth.urls')),
    path('api-token-refresh/', refresh_jwt_token),
    path('api-token-auth/', obtain_jwt_token),
    path('rest-auth/registration/', include('rest_auth.registration.urls'))
    ]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

cw/urls.py
from django.urls import path
from django.conf.urls import url

from .views import Load,Create,Main,Save,ListCross,Play

app_name = "cw"

urlpatterns = [
    path('cw/load', Load, name='load'),
    path('cw/create', Create, name='create'),
    path('cw/', Main, name='Main'),
    path('cw/save', Save, name='Save'),
    path('cw/all', ListCross.as_view(), name='list'),
    path('cw/play/<pk>', Play.as_view(), name='play'),
    ]

news/urls.py
from django.urls import path
from django.conf.urls import url,include
from .views import News,Article,CommentView,ReplyView,SearchView,Save_Art,scrappTop,scrappF,ScTapp
from django.views.decorators.csrf import csrf_exempt
from rest_framework import routers
from .api.views import ArticleViewSet
router = routers.DefaultRouter()
router.register(r'article-list',ArticleViewSet,'article-list')

app_name = "news"

urlpatterns = [
    path('news/', News.as_view(), name='news'),
    path('news/<slug>/', Article.as_view(), name='article'),
    path('news/comment/<slug>', CommentView, name='comment'),
    path('news/reply/<id>', ReplyView, name='reply'),
    path('new/add/', csrf_exempt(Save_Art), name='add'),
    path('search/',SearchView.as_view(),name='search'),
        path('new/test',scrappTop,name='st'),
        path('new/test2',scrappF,name='sf'),
        path('new/test3',ScTapp,name='sta'),
        path('api/', include(router.urls))
    ]

shortu/urls.py
from django.urls import path
from django.conf.urls import url

from .views import FormView,Submit,Follow,info

app_name = "shortu"

urlpatterns = [
    path('shortu/', FormView, name='form-view'),
    path('shortu/url/',Submit,name='submit'), 
    path('s/<shorturl>/',Follow,name='follow'),
    path('shortu/<shorturl>',info,name='info'),
     ]
    

cw/models.py
from django.db import models
from django.conf import settings

class Ans(models.Model):
    word = models.CharField(max_length=255)
    length = models.IntegerField(default=len(str(word)))
    popularity = models.IntegerField(default=1)
    used = models.IntegerField(default=1)
    solved =  models.IntegerField(default=1)
    hint = models.CharField(max_length=255)

    def __str__(self):
        return self.word
    def get_hints(self):
        return set(self.hint.split("-_-"))

class CrossWord(models.Model):
    board = models.TextField(default=' ')
    published = models.DateTimeField(auto_now_add=True, blank=True)
    def __str__(self):
        return str( self.id)
class Lead(models.Model):
    i = models.IntegerField(default=0)
    j = models.IntegerField(default=0)
    crosword = models.ForeignKey(CrossWord,on_delete=models.CASCADE,blank=True,null=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.SET_NULL,blank=True,null=True) 
    orientation = models.CharField(max_length=1)
    word = models.CharField(max_length=30)
    hint = models.CharField(max_length=255)
    pos = models.CharField(max_length= 3)
    def get_hint(self):
        return str(self.hint.split("-_-")[0])
    def int_post(self):
        return int(self.pos)+1
    def __str__(self):
        return self.word

news/models.py
from django.db import models
from django.conf import settings
from django.urls import reverse

import re

source = (
    (1, "tvKlan"),
    (2, "Faxweb"),
    (3, "top-channel")
)
cat = (
    (1, "Politike"),
    (2, "Aktualitet"),
    (3, "Sport"),
    (4, "Lifestyle"),
    (5, "Rajoni"),
    (6, "Bota"),
    (7, "Teknologji"),
    (8, "Kuriozitet"),
    (9, "Kulture"),
    (10, "Kronike"),
    (11, "Te Tjera")
)
class Artikull(models.Model):
    
    img = models.TextField(blank=True,null = True)
    title = models.CharField(max_length=255)
    content = models.TextField()
    slug = models.SlugField(unique=True,max_length=255)
    published = models.DateTimeField(auto_now_add=True, blank=True)
    video = models.BooleanField(default=False)
    nga = models.IntegerField(choices = source, default=1)
    categ = models.IntegerField(choices = cat, default=11)
    hits = models.IntegerField(default=0)
    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("news:article",kwargs={
            'slug':self.slug
        })
    def get_icon(self):
        e = re.compile(r'(https?://)?(www\.)?(youtube|youtu|youtube-nocookie)\.(com|be)/(watch\?v=|embed/|v/|.+\?v=)?(?P<id>[A-Za-z0-9\-=_]{11})')

        id = (e.match(self.img).group('id'))
        return ("https://img.youtube.com/vi/"+id+"/0.jpg")
class Comment(models.Model):
    artikull = models.ForeignKey(Artikull,on_delete=models.CASCADE)
    parent = models.ForeignKey('self', null=True, blank=True,on_delete=models.CASCADE)
    con = models.CharField(max_length = 255)
    user = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.SET_NULL,blank=True,null=True)
    postdate =  models.DateTimeField(auto_now_add=True)
    level = models.IntegerField(default=1)

    def children (self):
        return Comment.objects.filter(parent= self)

    def __str__(self):
        return self.con

shortu/models.py
from django.db import models
from django.conf import settings

class Link (models.Model):
    link =  models.CharField(max_length=255)
    shorturl = models.CharField(blank= True, null=True,max_length=150)
    vi = models.IntegerField(default=0)
    user = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.SET_NULL,blank=True,null=True)   
    def __str__(self):
        return self.link

cw/forms.py
from django import forms

class GenerateForm(forms.Form):
    # costom = forms.CharField(  label = "Prefered text", required = False ,widget= forms.TextInput(attrs={'class':'form-control'}))
    rows = forms.IntegerField (label = "Number of Rows")
    col =   forms.IntegerField (label = "Number of Columns")
    time = forms.FloatField(label = "Time to generate in minutes")
    

news/forms.py
from django import forms

class CommentForm(forms.Form):
    
    comment = forms.CharField( required = True ,widget= forms.Textarea(attrs={'class':'form-control'}))

class ReplyForm(forms.Form):
    reply = forms.CharField(required= True,widget = forms.TextInput(attrs={'class':'form-control'}))

shortu/forms.py
from django import forms


class UrlForm(forms.Form):
    url = forms.URLField( label = "Your long url",widget= forms.URLInput(attrs={'class':'form-control'}))
    #CharField( label = "Your long url")
    costom = forms.CharField(  label = "Prefered text", required = False ,widget= forms.TextInput(attrs={'class':'form-control'}))

cw/views.py
from django.shortcuts import render
from django.views.decorators.http import require_POST
from .models import Ans,CrossWord,Lead
from django.db.models import F
# json
from django import db
from django.http.response import HttpResponse
import json
import os
from django.http import JsonResponse

from django.views.generic import ListView, DetailView

from cw.wordx import Crossword
from cw.forms import GenerateForm

class ListCross(ListView):
    model = CrossWord
    template_name = "cw_list.html"
    paginate_by = 12
class Play(DetailView):
    model = CrossWord
    template_name = "play.html"
files = ["json_data_1.json","json_data_2.json","json_data_3.json","json_data_4.json","json_data_5.json"]
def Load(request):
    # Ans.objects.all().delete()
    # return HttpResponse("deleted")

    for file in files:
        with open("cw//"+file,'r') as f:
            data = json.load(f)
            
            for key,value in data.items():
                clues = value.split('-_-')[0]
                length = len(key)
                popularity = len(clues)
                ans_qs = Ans.objects.filter(word=key)
                ans_exists = ans_qs.exists()
                if ans_exists:
                    ans_qs.update(popularity=F('popularity')+popularity)
                else:
                    Ans.objects.create(word=key,length=length,popularity=popularity,hint = clues)
                
                db.connections.close_all()
def Create(request):
    if request.method == 'POST':
        rows = int(request.POST.get('rows'))
        col = int(request.POST.get('col'))
        time = float (request.POST.get('time'))
        print(rows,col,time)
        available_words = Ans.objects.values_list('word','hint')
        available_words = list(available_words)
        print(type(available_words[0]))
        new_C = Crossword(rows,col,'$',available_words)
        ret = (new_C.compute_crossword(time))
        r = {'board':ret}
        return HttpResponse(json.dumps(r),content_type="application/json")
    else:
        return HttpResponse(
            json.dumps({"nothing to see": "this isn't happening"}),
            content_type="application/json"
        )
@require_POST
def Save(request):
    if request.method == 'POST':
        user = request.user
        b = request.POST.getlist('grid[]')
        print(b)
    
        scw = CrossWord.objects.create(board= b)
        a = []
        d = []
        w = []
        rows = len(b)
        col = len(b[0])
        for i,r in enumerate (b):
            for j,c in enumerate (r):
                if c!='$':
                    if j==0 and b[i][j+1]!='$':
                        w.append([i,j,'a'])
                    if j!=0 and b[i][j-1] =='$':
                        if j==col-1:
                            pass
                        elif b[i][j+1] !='$':
                            w.append([i,j,'a'])
                    if i == 0 and b [i+1][j]!= '$':
                        w.append([i,j,'d'])
                    elif i!=0  and b[i-1][j] =='$':
                        if i== rows-1:
                            continue
                        elif b[i+1][j] !='$':
                            w.append([i,j,'d'])
        for index,el in enumerate(w):
            i = el[0]
            j = el[1]
            if el[2]=='a':
                
                
                step = ''
                point = b[i][j]
                while b[i][j]!='$' :
                    
                    step += b[i][j]
                    j+=1
                    if j== col:
                        break
                w[index].append(step)
            else:
                step = ''
                while b[i][j]!='$':
                    step += b[i][j]
                    i+=1
                    if i== rows:
                        break
                w[index].append(step)
            hint = Ans.objects.filter(word=step)[0].hint
            Lead.objects.create( crosword = scw,user = user,i =el[0],j=el[1],orientation= el[2],word = step,hint = hint,pos = index)
        
        return HttpResponse(b)

def Main(request):
    context = {
        'form':GenerateForm
    }
    return render(request,'cw.html',context)

news/api/views.py
from ..models import Artikull
from .serializer import ArticleSerializer
from django.db.models import Q
from rest_framework import viewsets

ak = '-05sgp9!deq=q1nltm@^^2cc+v29i(tyybv3v2t77qi66czazj'

class ArticleViewSet(viewsets.ReadOnlyModelViewSet):
    serializer_class = ArticleSerializer

    paginate_by = 20
    def get_queryset(self):
        q = None
        c=None
        try:
            c=self.request.META['HTTP_C']
            c = [int(ca) for ca in c.split(',')  ]
        except:
            pass
        print(type(c))
        s=None
        try:
            s=self.request.META['HTTP_S']
            s = [int(sa) for sa in s.split(',')  ]
        except:
            pass
        try:
            q=(self.request.META['HTTP_Q'])
        except:
            pass
        
        rk=(self.request.META['HTTP_X_KEY'])
        if ak!=rk:
            queryset = Artikull.objects.none()
        else:
            queryset = Artikull.objects.all()
        if c:
            queryset = Artikull.objects.filter(categ__in=c)
        if s:
            queryset = Artikull.objects.filter(nga__in=s)
        if q:
            queryset = queryset.filter(
                Q(title__icontains=q)|Q(content__icontains=q)
            )
            
        
        return queryset.order_by('-published')

        

news/views.py
from django.shortcuts import render
from django.views.generic import ListView,DetailView
from .forms import CommentForm,ReplyForm
from django.views.decorators.http import require_GET, require_POST
from django.http import HttpResponseRedirect,HttpResponse,JsonResponse
from django.db.models import Q
#scrap

import requests,re
from django.utils.text import slugify

from news.sc import scrappKlan as sk
from news.sc import scrappTop as st
from news.sc import scrappFax as sf
from .models import Artikull,Comment
from django.views.decorators.csrf import csrf_exempt
import json
@csrf_exempt
def Save_Art(request):
    sr = {  "tvKlan":1,
     "Faxweb":2,
     "top-channel":3 }
    cat_c = ["Politikë","Aktualitet", "Sport","Lifestyle","Rajoni","Bota","Teknologji", "Kuriozitet","Kulturë",
    "Kronikë"]
    if request.method == 'POST':
        data = json.loads(request.body)
        # print(data)
        title = data.get('title', None)
        content = data.get('content', None)
        img = data.get('img', None)
        slug  = create_slug(title)
        video = data.get('video', None)
        s = data.get('s', None)
        cat = data.get('cat', None)
        if cat in cat_c:
            cat= cat_c.index(cat)+1
        else:
            cat=11
        if video:
            video = True
        else:
            video = False
        qs = Artikull.objects.filter(title=title)
        exists = qs.exists()
        if not exists:
            a = Artikull.objects.create(title=title,content=content,img=img,slug=slug,video=video,nga=sr[s],categ=cat)
            return HttpResponseRedirect(a.get_absolute_url())    
        return HttpResponseRedirect(qs[0].get_absolute_url())
class News(ListView):
    queryset = Artikull.objects.order_by('-published')
    paginate_by = 12
    template_name = 'news.html'
    def get_context_data(self,**kwargs):
        context = super(News,self).get_context_data(**kwargs)
        
        context['sq'] = None       
        return context

class Article(DetailView):
    model = Artikull
    template_name = 'article.html'
    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        
        context['form'] = CommentForm
        context['reply'] = ReplyForm
        return context
class SearchView(ListView):
    template_name = 'news.html'
    
    paginate_by = 12
    def get_context_data(self,**kwargs):
        context = super(SearchView,self).get_context_data(**kwargs)
        query = self.request.GET.get('q')
        context['sq'] = query        
        return context
    def get_queryset(self):
        query = self.request.GET.get('q')
        print(query)
        object_list = Artikull.objects.filter(
                Q(title__icontains=query)|Q(content__icontains=query)
            )
        return object_list.order_by('-published')


@require_POST
def CommentView(request,slug):
    form = CommentForm(request.POST)
    artikull = Artikull.objects.filter(slug = slug)
    if form.is_valid():
        content = form.cleaned_data['comment']
        user = request.user
        
        new_comment = Comment.objects.create(user=user,artikull=artikull[0],con=content)

    
    return HttpResponseRedirect(artikull[0].get_absolute_url())
@require_POST
def ReplyView(request,id):
    parent = Comment.objects.filter(id= id)
    if parent.exists():
        parent = parent[0]
        form = ReplyForm(request.POST)
        if form.is_valid():
            con = form.cleaned_data['reply']
            user = request.user
            level = parent.level + 1
            if level > 3:
                parent = parent.parent
                level = 3
            new_reply = Comment.objects.create(user= user,parent=parent,con=con,level = level,artikull=parent.artikull)
            return HttpResponseRedirect(parent.artikull.get_absolute_url())
    return HttpResponseRedirect('/')

def create_slug(title, new_slug=None):
        slug = slugify(title, allow_unicode = True)
        if new_slug is not None:
            slug = new_slug
        qs = Artikull.objects.filter(slug=slug).order_by("-id")
        exists = qs.exists()
        if exists:
            new_slug = "%s-%s"%(slug, qs.first().id)
            return create_slug(title, new_slug=new_slug)
        return slug

def scrappTop(request):
    print('ddsdfsdfds')
    # st()
    res = sk()

    return JsonResponse(res) 
def ScTapp(request):
    res = st()
    return JsonResponse(res,safe=False)
def scrappF(request):
    print('ddsdfsdfds')
    # st()
    res = sf()

    return JsonResponse(res) 

templates/article.html
{% extends "base.html" %}{% load static %}
{% block title %}{{ object.title}}{% endblock title %}



{% block extrahead %}
<!-- Custom styles for this template -->
<script
  src="https://code.jquery.com/jquery-3.4.1.min.js"
  integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo="
  crossorigin="anonymous"></script>
  
<script src="{% static 'js/bootstrap.min.js' %}"></script>
{% endblock extrahead %}
  
{% block content %}

<nav class="navbar navbar-expand-lg navbar-dark bg-dark static-top">
    <div class="container">
      <a class="navbar-brand" href="/">Af-u
      <span class="sr-only">(current)</span></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a class="nav-link" href="/shortu/">URL Shortner
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/cw/">Crosswords</a>
          </li>
                    <li class="nav-item">
            <a class="nav-link" href="/news/">News Agregator</a>
          </li>
          <li class="nav-item">
            {% if user.is_authenticated %}
                      
            <a class="nav-link" href="{% url 'account_logout'%}">Log out!</a>
            {% else %}
            <a class="nav-link" href="{% url 'account_login'%}">Log in!</a>
            {% endif %}

          </li>
        </ul>
      </div>
    </div>
  </nav>

<!-- Page Content -->
  <div class="container">

    <div class="row">

      <!-- Post Content Column -->
      <div class="col-lg-8">

        <!-- Title -->
        <h1 class="mt-4">{{ object.title }}</h1>

       
        <hr>

        <!-- Date/Time -->
        <p>{{ object.published }}</p>

        <hr>
        {% if object.video %}
        <iframe width="854" height="480"
src="{{object.img}}">
</iframe>
        {% else %}
        <img class="img-fluid rounded" src="{{object.img}}" alt="">
        {% endif %}
        <!-- Preview Image -->
        <img class="img-fluid rounded" src="{{object.img}}" alt="">

        <hr>

        <!-- Post Content -->
        <p class="lead">{{object.content|safe}}</p>
        <hr>
        <a href="{% url 'news:news' %}">
        <button class="btn btn-danger" >Go back</button>
        </a>
        <hr>

        <!-- Comments Form -->
        <div class="card my-4">
          <h5 class="card-header">Komento:</h5>
          <div class="card-body">
            <form action="{% url 'news:comment' object.slug %}" method="POST">
            {% csrf_token %}
              <div class="form-group">
              {{form.comment}}
               
              </div>
              {% if user.is_authenticated %}
              <button type="submit" class="btn btn-primary">Submit</button>
              {% else %}
              <a class= "btn btn-primary" href="{% url 'account_signup'%}">Sign Up</a>
              <a class= "btn btn-primary" href="{% url 'account_login'%}">Login</a>
              {% endif %}
              

            </form>
          </div>
        </div>
        <hr>
        

{% for comment in artikull.comment_set.all %}
        {% if comment.level == 1 %}
        
        
        
      <div class="card">
	    <div class="card-body">
	        <div class="row">
        	    <div class="col-md-2">
        	        
        	        <p class="text-secondary text-center">{{comment.postdate|timesince}}</p>
        	    </div>
        	    <div class="col-md-10">
        	        <p>
        	            <strong>{{comment.user}}</strong>
        	       </p>
        	       <div class="clearfix"></div>
        	        <p>{{comment.con}}</p>
                  <p>
                  <form action="{% url 'news:reply' comment.id %}" method="POST">
                    {% csrf_token %}
                    <div class="form-group">
                    {{reply.reply}}
                    
                    </div>
                    {% if user.is_authenticated %}
                    <button type="submit" class="btn btn-primary">Reply</button>
                    {% else %}
                    <a class= "btn btn-primary" href="{% url 'account_signup'%}">Sign Up</a>
                    <a class= "btn btn-primary" href="{% url 'account_login'%}">Login</a>
                    {% endif %}
                    

                  </form>
        	            
        	        </p>
        	    </div>
	        </div>
	        	<div class="card card-inner">
              {% if comment.children  %}
              {% for child in comment.children %}
              
              
              
              
            	    <div class="card-body">
            	        <div class="row">
                    	    <div class="col-md-2">
                    	        <p class="text-secondary text-center">{{ child.postdate|timesince}}</p>
                    	    </div>
                    	    <div class="col-md-10">
                    	        <p><strong>{{child.user}}</strong></p>
                    	        <p>{{ child.con }}</p>
                    	        <p>
                    	            <form action="{% url 'news:reply' child.id %}" method="POST">
                    {% csrf_token %}
                    <div class="form-group">
                    {{reply.reply}}
                    
                    </div>
                    {% if user.is_authenticated %}
                    <button type="submit" class="btn btn-primary">Reply</button>
                    {% else %}
                    <a class= "btn btn-primary" href="{% url 'account_signup'%}">Sign Up</a>
                    <a class= "btn btn-primary" href="{% url 'account_login'%}">Login</a>
                    {% endif %}
                    

                  </form>
                    	       </p>
                    	    </div>
            	        </div>
            	    </div>
                  <div class="card card-inner">
              {% if child.children  %}
              {% for l3 in child.children %}
              
              
              
              
            	    <div class="card-body">
            	        <div class="row">
                    	    <div class="col-md-2">
                    	        <p class="text-secondary text-center">{{ l3.postdate|timesince}}</p>
                    	    </div>
                    	    <div class="col-md-10">
                    	        <p><strong>{{l3.user}}</strong></p>
                    	        <p>{{ l3.con }}</p>
                    	        <p>
                    	            <form action="{% url 'news:reply' l3.id %}" method="POST">
                    {% csrf_token %}
                    <div class="form-group">
                    {{reply.reply}}
                    
                    </div>
                    {% if user.is_authenticated %}
                    <button type="submit" class="btn btn-primary">Reply</button>
                    {% else %}
                    <a class= "btn btn-primary" href="{% url 'account_signup'%}">Sign Up</a>
                    <a class= "btn btn-primary" href="{% url 'account_login'%}">Login</a>
                    {% endif %}
                    

                  </form>
                    	       </p>
                    	    </div>
            	        
            	    
                  {% endfor %}
              {% endif %}
              </div></div>
                  {% endfor %}
              {% endif %}
	            </div>
	    </div>
	</div>
  {% endif %}
    {% endfor %}
{% endblock content %}

templates/cw.html
{% extends "base.html" %}
{% load static %}
{% block title %}Crosswords{% endblock title %}

{% block extrahead %}
<script
  src="https://code.jquery.com/jquery-3.4.1.min.js"
  integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo="
  crossorigin="anonymous"></script>

{% endblock extrahead %}

{% block content %}

 <nav class="navbar navbar-expand-lg navbar-dark bg-dark static-top">
    <div class="container">
      <a class="navbar-brand" href="/">Af-u</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'cw:Main' %}">Generate Crosswords
              <span class="sr-only">(current)</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'cw:list' %}">All Crosswords</a>
          </li>
          <li class="nav-item">
            {% if user.is_authenticated %}
                      
            <a class="nav-link" href="{% url 'account_logout'%}">Log out!</a>
            {% else %}
            <a class="nav-link" href="{% url 'account_login'%}">Log in!</a>
            {% endif %}

          </li>
        </ul>
      </div>
    </div>
  </nav>
<div class='container'>
<form action='/cw/create' method= "POST" id = "create" >
    {% csrf_token %}
    <div class="form-group">
    <label> Input number of rows:</label>
    {{form.rows}}</div>
    <div class="form-group">
    <label> Input number of cols:</label>
    {{form.col}}</div>
    <div class="form-group">
    <label> Input time to generate:</label>
    {{form.time}}</div>
    <div id="results"></div> <!-- errors go here -->
    <button type="submit"  class="btn btn-primary">Submit</button>
</form>
</div>
<div class='container' id = 'preview'>
    <form method='POST' id='save'>
    {% csrf_token %}
    <table id='table' class='table-bordered'>
    </table>

    </form>
</div>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script>

$(function() {
  $('input').addClass('form-control');
});

// Submit post on submit
$('#create').on('submit', function(event){
    event.preventDefault();
    console.log("form submitted!")  // sanity check
    generate();
});

var  board;
// AJAX for posting
// AJAX for posting
function generate() {
    console.log("create post is working!") // sanity check
    $.ajax({
        url : "{% url 'cw:create' %}", // the endpoint
        type : "POST", // http method
        data : { rows : $('#id_rows').val() ,col : $('#id_col').val(),time : $('#id_time').val(),
        csrfmiddlewaretoken: document.getElementsByName('csrfmiddlewaretoken')[0].value }, // data sent with the post request
     
        // handle a successful response
        success : function(json) {
            $('#id-col').val('');
            $('#id-time').val('');
            $('#id-rows').val(''); // remove the value from the input
            console.log("Json");
            board=json['board'];
            $('#table tr').remove();
            var $table = $('#table');
            
            var row, cell;
            for(var i=0; i<board.length; i++){
            row = $( '<tr />' );
            
            for(var j=0; j<board[i].length; j++){
                    //class="text-white bg-dark"
                    let c =board[i][j];
                    if(c== '$'){
                        cell = $('<td class="bg-dark">'+'</td>')
                    }else{
            cell = $('<td>'+c+'</td>')
                    }

            row.append( cell );
            //console.log(board[i][j]);
            }
            
            $table.append( row );
            }
            $('#save button').remove();
            $('#save').append($('<button type="submit"  class="btn btn-primary">Save</button>'))

            // Submit post on submit
            $('#save').on('submit', function(event){
            event.preventDefault();
            console.log("form submitted!")  // sanity check
            save();
            });
            

            console.log($table);
            console.log(board); // log the returned json to the console
            console.log("success"); // another sanity check
        },

        // handle a non-successful response
        error : function(xhr,errmsg,err) {
            $('#results').html("<div class='alert-box alert radius' data-alert>Oops! We have encountered an error: "+errmsg+
                " <a href='#' class='close'>&times;</a></div>"); // add the error to the dom
            console.log(xhr.status + ": " + xhr.responseText); // provide a bit more info about the error to the console
        }
    });
};

function save() {
    console.log("saving") // sanity check
$.ajax({
        url : "{% url 'cw:Save' %}", // the endpoint
        type : "POST", // http method
        data : { 'grid' : board ,
        csrfmiddlewaretoken: document.getElementsByName('csrfmiddlewaretoken')[1].value }, // data sent with the post request
     
        // handle a successful response
        success : function(link) {
            console.log(link);
                    },

        // handle a non-successful response
        error : function(xhr,errmsg,err) {
            $('#results').html("<div class='alert-box alert radius' data-alert>Oops! We have encountered an error: "+errmsg+
                " <a href='#' class='close'>&times;</a></div>"); // add the error to the dom
            console.log(xhr.status + ": " + xhr.responseText); // provide a bit more info about the error to the console
        }
    });
};
</script>
<script>
{% endblock content %}